# Build stage para apps/client y apps/admin
FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/server/package.json ./apps/server/
COPY apps/admin/package.json ./apps/admin/
COPY apps/client/package.json ./apps/client/

RUN npm install

COPY apps/admin ./apps/admin
COPY apps/client ./apps/client

# Compilar ambas aplicaciones web
RUN npm --workspace=apps/admin run build
RUN npm --workspace=apps/client run build

# Nginx Production Stage
FROM nginx:alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar artefactos de compilación
COPY --from=builder /app/apps/client/dist /usr/share/nginx/html/client
COPY --from=builder /app/apps/admin/dist /usr/share/nginx/html/admin

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
